export const languages = [
  // Europa
  {
    code: 'es',
    name: 'Spanish',
    native: 'Español',
    flag: '🇪🇸',
    active: true,
  },
  {
    code: 'ca',
    name: 'Catalan',
    native: 'Català',
    flag: '🇪🇸',
    active: true,
  },
  {
    code: 'eu',
    name: 'Basque',
    native: 'Euskara',
    flag: '🇪🇸',
    active: true,
  },
  {
    code: 'gl',
    name: 'Galician',
    native: 'Galego',
    flag: '🇪🇸',
    active: true,
  },
  {
    code: 'ast',
    name: 'Asturian',
    native: 'Asturianu',
    flag: '🇪🇸',
    active: true,
    interfaceHidden: true, // Easter egg: accessible via URL but not in language selector
  },
  {
    code: 'ara',
    name: 'Aragonese',
    native: 'Aragonés',
    flag: '🇪🇸',
    active: true,
    interfaceHidden: true,
  },
  {
    code: 'mur',
    name: 'Murcian',
    native: 'Murciano',
    flag: '🇪🇸',
    active: true,
    interfaceHidden: true,
  },
  {
    code: 'and',
    name: 'Andalusian',
    native: 'Andalú',
    flag: '🇪🇸',
    active: true,
    interfaceHidden: true,
  },
  {
    code: 'can',
    name: 'Canarian',
    native: 'Canario',
    flag: '🇮🇨',
    active: true,
    interfaceHidden: true,
  },
  {
    code: 'ext',
    name: 'Extremaduran',
    native: 'Estremeñu',
    flag: '🇪🇸',
    active: true,
    interfaceHidden: true,
  },
  {
    code: 'cnt',
    name: 'Cantabrian',
    native: 'Cántabru',
    flag: '🇪🇸',
    active: true,
    interfaceHidden: true,
  },
  {
    code: 'en',
    name: 'English',
    native: 'English',
    flag: '🇬🇧',
    active: true,
  },
  {
    code: 'fr',
    name: 'French',
    native: 'Français',
    flag: '🇫🇷',
    active: true,
  },
  {
    code: 'de',
    name: 'German',
    native: 'Deutsch',
    flag: '🇩🇪',
    active: true,
  },
  {
    code: 'it',
    name: 'Italian',
    native: 'Italiano',
    flag: '🇮🇹',
    active: true,
  },
  {
    code: 'pt',
    name: 'Portuguese',
    native: 'Português',
    flag: '🇵🇹',
    active: true,
  },
  {
    code: 'nl',
    name: 'Dutch',
    native: 'Nederlands',
    flag: '🇳🇱',
    active: true,
  },
  {
    code: 'ru',
    name: 'Russian',
    native: 'Русский',
    flag: '🇷🇺',
    active: true,
  },
  {
    code: 'pl',
    name: 'Polish',
    native: 'Polski',
    flag: '🇵🇱',
    active: true,
  },
  {
    code: 'sv',
    name: 'Swedish',
    native: 'Svenska',
    flag: '🇸🇪',
    active: true,
  },
  {
    code: 'da',
    name: 'Danish',
    native: 'Dansk',
    flag: '🇩🇰',
    active: true,
  },
  {
    code: 'no',
    name: 'Norwegian',
    native: 'Norsk',
    flag: '🇳🇴',
    active: true,
  },
  {
    code: 'fi',
    name: 'Finnish',
    native: 'Suomi',
    flag: '🇫🇮',
    active: true,
  },
  {
    code: 'ro',
    name: 'Romanian',
    native: 'Română',
    flag: '🇷🇴',
    active: true,
  },
  {
    code: 'cs',
    name: 'Czech',
    native: 'Čeština',
    flag: '🇨🇿',
    active: true,
  },
  {
    code: 'hu',
    name: 'Hungarian',
    native: 'Magyar',
    flag: '🇭🇺',
    active: true,
  },
  {
    code: 'el',
    name: 'Greek',
    native: 'Ελληνικά',
    flag: '🇬🇷',
    active: true,
  },
  {
    code: 'uk',
    name: 'Ukrainian',
    native: 'Українська',
    flag: '🇺🇦',
    active: true,
  },
  {
    code: 'bg',
    name: 'Bulgarian',
    native: 'Български',
    flag: '🇧🇬',
    active: true,
  },
  {
    code: 'sr',
    name: 'Serbian',
    native: 'Српски',
    flag: '🇷🇸',
    active: true,
  },
  {
    code: 'hr',
    name: 'Croatian',
    native: 'Hrvatski',
    flag: '🇭🇷',
    active: true,
  },
  {
    code: 'sk',
    name: 'Slovak',
    native: 'Slovenčina',
    flag: '🇸🇰',
    active: true,
  },
  {
    code: 'sl',
    name: 'Slovenian',
    native: 'Slovenščina',
    flag: '🇸🇮',
    active: true,
  },

  // Asia
  {
    code: 'zh',
    name: 'Chinese (Simplified)',
    native: '中文',
    flag: '🇨🇳',
    active: true,
  },
  {
    code: 'ja',
    name: 'Japanese',
    native: '日本語',
    flag: '🇯🇵',
    active: true,
  },
  {
    code: 'ko',
    name: 'Korean',
    native: '한국어',
    flag: '🇰🇷',
    active: true,
  },
  {
    code: 'ar',
    name: 'Arabic',
    native: 'العربية',
    flag: '🇸🇦',
    active: true,
  },
  {
    code: 'hi',
    name: 'Hindi',
    native: 'हिन्दी',
    flag: '🇮🇳',
    active: true,
  },
  {
    code: 'tr',
    name: 'Turkish',
    native: 'Türkçe',
    flag: '🇹🇷',
    active: true,
  },
  {
    code: 'he',
    name: 'Hebrew',
    native: 'עברית',
    flag: '🇮🇱',
    active: true,
  },
  {
    code: 'fa',
    name: 'Persian',
    native: 'فارسی',
    flag: '🇮🇷',
    active: true,
  },
  {
    code: 'ur',
    name: 'Urdu',
    native: 'اردو',
    flag: '🇵🇰',
    active: true,
  },
  {
    code: 'bn',
    name: 'Bengali',
    native: 'বাংলা',
    flag: '🇧🇩',
    active: true,
  },

  // Southeast Asia & Others
  {
    code: 'id',
    name: 'Indonesian',
    native: 'Bahasa Indonesia',
    flag: '🇮🇩',
    active: true,
  },
  {
    code: 'ms',
    name: 'Malay',
    native: 'Bahasa Melayu',
    flag: '🇲🇾',
    active: true,
  },
  {
    code: 'vi',
    name: 'Vietnamese',
    native: 'Tiếng Việt',
    flag: '🇻🇳',
    active: true,
  },
  {
    code: 'th',
    name: 'Thai',
    native: 'ไทย',
    flag: '🇹🇭',
    active: true,
  },
  {
    code: 'tl',
    name: 'Filipino',
    native: 'Filipino',
    flag: '🇵🇭',
    active: true,
  },

  // Americas
  {
    code: 'pt-br',
    name: 'Portuguese (Brazil)',
    native: 'Português (Brasil)',
    flag: '🇧🇷',
    active: true,
  },

  // Africa
  {
    code: 'sw',
    name: 'Swahili',
    native: 'Kiswahili',
    flag: '🇰🇪',
    active: true,
  },
  {
    code: 'af',
    name: 'Afrikaans',
    native: 'Afrikaans',
    flag: '🇿🇦',
    active: true,
  },
]

export default languages
